---
title: "alpha-diversity"
output:
  html_notebook:
    code_fold: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(plyr)
library(dplyr)
library(RColorBrewer)
source("../../common.R")
chaoTheme <- theme(axis.title=element_text(size=16,face="bold"),
                   text=element_text(size=14,face="bold"))

do.write<-F
```

#  Load data
* shannon index
* CTgroup phenotype
```{r, warning=FALSE}
# Load thr1st,patSum,pat3M,Nthr,evaDat,pat3M0,pat3M1
load("../../../Result/Phenotype/both/phenotype.BOTH.Rmd.RData")
# Load patDNA0,patDNA3
load("../../../Result/Phenotype/both/FecalDNA.BOTH.Rmd.RData")
#FDNA.NS,FDNA.NPC.pick2,FDNA.NPC.pick3,FDNA.NS.pick2,FDNA.NS.pick3
load(md5("../../../Result/TimeSeries/NPC/FDNA.NPC.picks.RData","03e2f415886ab16c2a0433056a59522b"))
# Load FDNA_A.eva2 generated by timeSeriesView.Rmd
shan <- read.table("shan.txt", header = T)
#Load phe.all.NPC,phe.gut.NPC,phe.base.gut.NPC,NPC.PID,NPC.ATB.PID
load(md5("../../../Result/Phenotype/NPC/NPC62.phe.RData","8e0c62576fff1b421f1c197cb6368957" ))
```

# Curation

```{r}
#mShan0 <- merge(patDNA0, shan,by="DNAID")
mShan0 <- FDNA.NPC.pick2
mShan0$ATBR <- ifelse(mShan0$PID%in%atb.risk.PID,T,F)
#mShan0$biweekly <- round(as.numeric(mShan0$Day,units="weeks")/2,0)*2

mShan3 <- FDNA.NPC.pick3
mShan3$ATBR <- ifelse(mShan3$PID%in%atb.risk.PID,T,F)
```

#Visualization

```{r}
p0 <- ggplot(FDNA.NPC.pick2%>%filter(ATB02==F), aes(x=Ws, y=shan, fill=BE3))+
  geom_boxplot(outlier.shape=NA)+theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="alpha diversity", x="Weeks", y="Shannon index")+
  scale_fill_brewer(palette="Set1") +
  stat_compare_means(label="p.format")
p0
p1 <- ggplot(FDNA.NPC.pick3%>%filter(ATB02==F), aes(x=Ms, y=shan, fill=BE3))+
  geom_boxplot(outlier.shape=NA)+theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(x="Weeks", y="Alpha diversity(shannon)")+
  scale_fill_brewer(palette="Set1") +
  #stat_compare_means(label="p.signif")
  stat_compare_means(label="p.format")
p1
p2 <- ggplot(FDNA.NPC.pick3%>%filter(ATB02==F), aes(x=Ms, y=shan, fill=BE3))+
  geom_boxplot(outlier.shape=NA)+theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.1)) +
  labs(x="Month", y="Alpha diversity(shannon)",color="Response") +
  scale_fill_brewer(palette="Set1") +
  stat_compare_means(label="p.signif")
p2
if(do.write){
  ggsave(p0,file="../../../Result/AlphaDiversity/alpha.w.p0.plot.pdf",width=8,heigh=3)
  ggsave(p1,file="../../../Result/AlphaDiversity/alpha.w.p1.plot.pdf",width=4,heigh=3)
  ggsave(p2,file="../../../Result/AlphaDiversity/alpha.Ms.p2.plot.pdf",width=4,heigh=3)

}
```
```{r}
range((FDNA.NPC.pick3%>%filter(ATB02==F))$shan)
```

**smooth lines**
```{r}
tmp.pick1 <- FDNA.NS.pick3%>%filter(ATB02==F&Ws!="W18")
p1.5 <- ggplot(FDNA.NPC.pick3%>%filter(ATB02==F), aes(x=Day, y=shan))+
  geom_point(aes(color=BE3),alpha=.5,size=1) +
  labs(x="Weeks", y="Alpha diversity (Shannon)",color="Response") +
  scale_fill_brewer(palette="Set1") + scale_color_brewer(palette="Set1") +
  scale_x_continuous(breaks=seq(0,126,28),labels=paste0("M",seq(0,4,1))) +
  stat_smooth(aes(group=BE3,color=BE3),alpha=.2) + theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.75,0.1))

p1.5
tmp.pick2 <- FDNA.NS.pick2%>%filter(ATB02==F&Ws!="W18")

p2.5 <- ggplot(tmp.pick2, aes(x=Day, y=shan))+
  geom_point(aes(color=BE3),alpha=.5,size=1) +
  labs(x="Weeks", y="Alpha diversity (Shannon)",color="Response") +
  scale_fill_brewer(palette="Set1") + scale_color_brewer(palette="Set1") +
  scale_x_continuous(breaks=seq(0,126,14),labels=paste0("W",seq(0,18,2))) +
  stat_smooth(aes(group=BE3,color=BE3),alpha=.2) + theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.75,0.1))

p2.5
if(do.write){
  ggsave(p1.5,file="../../../Result/AlphaDiversity/alpha.Ms.smooth.plot.pdf",width=5,heigh=3)
  ggsave(p2.5,file="../../../Result/AlphaDiversity/alpha.Ws.smooth.plot.pdf",width=5,heigh=3)
}
```


**suppl. BE2**
```{r, fig.width=4,fig.height=1.5}
p02 <- ggplot(FDNA.NPC.pick2%>%filter(ATB02==F), aes(x=Ws, y=shan, fill=BE2))+
  geom_boxplot(outlier.shape=NA)+theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(title="alpha diversity", x="Weeks", y="Shannon index")+
  scale_fill_brewer(palette="Set1") +
  stat_compare_means(label="p.format")
p02
p12 <- ggplot(FDNA.NPC.pick3%>%filter(ATB02==F), aes(x=Ms, y=shan, fill=BE2))+
  geom_boxplot(outlier.shape=NA)+theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.2)) +
  labs(x="Weeks", y="Alpha diversity(shannon)")+
  scale_fill_brewer(palette="Set1") +
  #stat_compare_means(label="p.signif")
  stat_compare_means(label="p.format")
p12
p22 <- ggplot(FDNA.NPC.pick3%>%filter(ATB02==F), aes(x=Ms, y=shan, fill=BE2))+
  geom_boxplot(outlier.shape=NA)+theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.7,0.1)) +
  labs(x="Month", y="Alpha diversity(shannon)",color="Response") +
  scale_fill_brewer(palette="Set1") +
  stat_compare_means(label="p.signif")
p22

p2.52 <- ggplot(tmp.pick2, aes(x=Day, y=shan))+
  geom_point(aes(color=BE3),alpha=.3) +
  labs(x="Weeks", y="Alpha diversity(shannon)",color="Response") +
  scale_fill_brewer(palette="Set1") + scale_color_brewer(palette="Set1") +
  scale_x_continuous(breaks=seq(0,126,14),labels=paste0("W",seq(0,18,2))) +
  stat_smooth(aes(group=BE2,color=BE2),alpha=.2) + theme_classic() +
  theme(legend.direction = "horizontal",legend.position=c(0.55,0.1))
p2.52
if(do.write){
  ggsave(p02,file="../../../Result/AlphaDiversity/alpha.w.p0.BE2.plot.pdf",width=8,heigh=3)
  ggsave(p12,file="../../../Result/AlphaDiversity/alpha.w.p1.BE2.plot.pdf",width=4,heigh=3)
  ggsave(p22,file="../../../Result/AlphaDiversity/alpha.Ms.p2.BE2.plot.pdf",width=4,heigh=3)
  ggsave(p2.52,file="../../../Result/AlphaDiversity/alpha.Ws.BE2.smooth.plot.pdf",width=5,heigh=3)
}
```

#shanoon and TMB
```{r}
TMB.info <- read.csv("../../../Result/HLA/57_PD1_NPC.2020-4-14.csv")

FDNA.NPC.pick3.tmb <- merge(FDNA.NPC.pick3,TMB.info[,c("PID","TMBnew")],by="PID")

ggplot(FDNA.NPC.pick3.tmb%>%filter(ATB02==F&Ws=="W0"), aes(y=TMBnew, x=BE2, fill=BE2))+ geom_boxplot() +stat_compare_means()
ggplot(FDNA.NPC.pick3.tmb%>%filter(ATB02==F&Ws=="W0"), aes(y=TMBnew, x=BE3, fill=BE3))+ geom_boxplot() +stat_compare_means()

ggplot(FDNA.NPC.pick3.tmb%>%filter(ATB02==F&Ws=="W0"), aes(y=TMBnew, x=shan, color=BE2))+
  geom_point(outlier.shape=NA)+theme_classic() +
  #theme(legend.direction = "horizontal",legend.position=c(0.8,0.5)) +
  labs(y="TMB", x="Alpha diversity(shannon)",color="Response") +
  scale_fill_brewer(palette="Set1")
```




























